### ISSUE TITLE
Incorrect response for admin.poolz.finance/lock-token-whitelists

### ISSUE THREAD

**Issue by DVitaliy** [The-Poolz/APIs#81]
[Strapi collection LockTokenWhitelists](https://admin.poolz.finance/admin/plugins/content-manager/collectionType/application::lock-token-whitelist.lock-token-whitelist?page=1&pageSize=10&_sort=id:DESC) has row #52 with type value `Envelope`
![Xnip2022-07-14_16-57-35](https://user-images.githubusercontent.com/1593183/179000783-1ea7cd06-9629-4de0-bae6-2a4251d24878.jpg)

But response of `admin.poolz.finance/lock-token-whitelists` for #52 has incorrect value
![Xnip2022-07-14_16-58-51](https://user-images.githubusercontent.com/1593183/179001297-244f2ea0-bcce-474e-afdb-717d5f109a2d.jpg)

**Comment by Lomet** [comment]
There is fire wall with Cash, take up to 20 min after data change
